// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromptBridge.API.Data;

#nullable disable

namespace PromptBridge.API.Migrations
{
    [DbContext(typeof(PromptBridgeContext))]
    [Migration("20250813132846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptBridge.API.Models.AIProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AIProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "",
                            BaseUrl = "https://api.openai.com/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OpenAI GPT-3.5/4 API",
                            IsActive = true,
                            Name = "OpenAI GPT"
                        },
                        new
                        {
                            Id = 2,
                            ApiKey = "",
                            BaseUrl = "https://api.anthropic.com/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anthropic Claude API",
                            IsActive = true,
                            Name = "Anthropic Claude"
                        },
                        new
                        {
                            Id = 3,
                            ApiKey = "",
                            BaseUrl = "https://generativelanguage.googleapis.com/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Google Gemini API",
                            IsActive = true,
                            Name = "Google Gemini"
                        },
                        new
                        {
                            Id = 4,
                            ApiKey = "",
                            BaseUrl = "https://api.x.ai/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "xAI Grok-2 API",
                            IsActive = true,
                            Name = "Grok"
                        },
                        new
                        {
                            Id = 5,
                            ApiKey = "",
                            BaseUrl = "https://openrouter.ai/api/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OpenRouter - Multiple AI Models (OpenAI, Anthropic, Google, Meta)",
                            IsActive = true,
                            Name = "OpenRouter"
                        },
                        new
                        {
                            Id = 6,
                            ApiKey = "",
                            BaseUrl = "https://api.cohere.ai/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cohere Command-R API",
                            IsActive = true,
                            Name = "Cohere"
                        },
                        new
                        {
                            Id = 7,
                            ApiKey = "",
                            BaseUrl = "https://api-inference.huggingface.co",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HuggingFace Open Source AI Models",
                            IsActive = true,
                            Name = "HuggingFace"
                        },
                        new
                        {
                            Id = 8,
                            ApiKey = "",
                            BaseUrl = "https://api.vercel.com/v1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vercel AI SDK - 100+ AI Models (OpenAI, Anthropic, xAI, Google, Meta)",
                            IsActive = true,
                            Name = "Vercel"
                        });
                });

            modelBuilder.Entity("PromptBridge.API.Models.PromptRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AIProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Response")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AIProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("PromptRequests");
                });

            modelBuilder.Entity("PromptBridge.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromptBridge.API.Models.PromptRequest", b =>
                {
                    b.HasOne("PromptBridge.API.Models.AIProvider", "AIProvider")
                        .WithMany("PromptRequests")
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptBridge.API.Models.User", "User")
                        .WithMany("PromptRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptBridge.API.Models.AIProvider", b =>
                {
                    b.Navigation("PromptRequests");
                });

            modelBuilder.Entity("PromptBridge.API.Models.User", b =>
                {
                    b.Navigation("PromptRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
